project_id = "qwtioetvfvfflbkzbpfu"

[functions.call-agent]
verify_jwt = false

[functions.chat-with-ai]
verify_jwt = true

[functions.validate-agent-response]
verify_jwt = true

[functions.generate-cognitive-insights]
verify_jwt = true

[functions.batch-execute-tests]
verify_jwt = true

[functions.calculate-agreement]
verify_jwt = true

[functions.generate-improvement-report]
verify_jwt = true

[functions.generate-tenant-image]
verify_jwt = true

[functions.execute-security-test]
verify_jwt = true

[functions.generate-security-compliance-report]
verify_jwt = true