project_id = "qwtioetvfvfflbkzbpfu"

[functions.call-agent]
verify_jwt = false

[functions.validate-agent-response]
verify_jwt = true

[functions.generate-cognitive-insights]
verify_jwt = true

[functions.batch-execute-tests]
verify_jwt = true

[functions.calculate-agreement]
verify_jwt = true